name: flutter_scaffold
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 2.2.0

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.15.8
  audio_recorder: ^1.0.1
  carousel_slider: ^1.3.1
  transparent_image: ^1.0.0
  url_launcher: ^5.2.1
  cached_network_image: 1.1.3
  smooth_star_rating: ^1.0.3
  http: ^0.12.0+2
  provider: ^3.1.0+1
  flutter_secure_storage: ^3.3.1+1
  shared_preferences: ^0.4.3
  fluttertoast: ^3.1.3
  built_collection: ^4.2.2
  built_value: ^6.6.0
  redux: ^3.0.0
  flutter_redux: ^0.5.0
  moor_flutter: ^2.0.0
  json_annotation: ^3.0.0
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  badges: ^1.1.0
  holding_gesture: ^0.0.3
  permission_handler: ^4.0.0


dev_dependencies:
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter

  built_value_generator: ^6.6.0
  moor_generator: ^2.0.1
  build_runner:
  json_serializable: ^3.0.0
  test: ^1.6.1
  mockito: ^4.1.0

  flutter_launcher_icons: "^0.7.3"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon.jpeg"

#flutter_icons:
#  android: true
#  ios: true
#  image_path: "assets/icon/icon.png"
#  adaptive_icon_foreground: "assets/icon/icon.png"
#  adaptive_icon_background: "#000000"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true


  assets:
    - assets/i18n/en.json
    - assets/i18n/fr.json
    - assets/i18n/ar.json
    - assets/images/
    - assets/

  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/lato/Lato-Regular.ttf
        - asset: assets/fonts/lato/Lato-RegularItalic.ttf
          style: italic
        - asset: assets/fonts/lato/Lato-Bold.ttf
          weight: 700
        - asset: assets/fonts/lato/Lato-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/lato/Lato-Black.ttf
          weight: 900
        - asset: assets/fonts/lato/Lato-BlackItalic.ttf
          weight: 900
          style: italic
        - asset: assets/fonts/lato/Lato-Light.ttf
          weight: 300
        - asset: assets/fonts/lato/Lato-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/lato/Lato-Thin.ttf
          weight: 100
        - asset: assets/fonts/lato/Lato-ThinItalic.ttf
          weight: 100
          style: italic
    - family: Dubai
      fonts:
        - asset: assets/fonts/dubai/Dubai-Regular.ttf
        - asset: assets/fonts/dubai/Dubai-Light.ttf
          weight: 300
        - asset: assets/fonts/dubai/Dubai-Bold.ttf
          weight: 700
        - asset: assets/fonts/dubai/Dubai-Medium.ttf
          weight: 900

# For details regarding fonts from package dependencies,
# see https://flutter.dev/custom-fonts/#from-packages
# flutter packages pub run build_runner watch --delete-conflicting-outputs
#rw.yegobox.shop_o1
##flutter pub run flutter_launcher_icons:main

#flutter build appbundle  --build-number 2.2.0